# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  # Required until https://github.com/jupyterhub/repo2docker/pull/1196 is merged
  - jupyterhub-singleuser>=3.0,<4.0
  # Set default python version to 3.10 - repo2docker sets it to 3.7 instead by default,
  # which can limit us to older package versions
  - python=3.10
  # Add other packages here
  # -
