# Re-tag staging SHA-tagged image with git tag and 'latest'
# tags can be anything, but typically calver string (2022.12.02)
name: Retag
on:
  push:
    tags:
    - '*'

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  retag-using-calver:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Job Environment Variables
      run: |
        SHA12="${GITHUB_SHA::12}"
        TAG="${GITHUB_REF##*/}"
        echo "SHA12=${SHA12}" >> $GITHUB_ENV
        echo "TAG=${TAG}" >> $GITHUB_ENV

    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Pull Image for Corresponding GitHub Commit
      run: |
        docker pull quay.io/cryointhecloud/cryo-hub-image:${SHA12}

    - name: Retag Images
      run: |
        docker tag cryointhecloud/cryo-hub-image:${SHA12} quay.io/cryointhecloud/cryo-hub-image:latest
        docker tag cryointhecloud/cryo-hub-image:${SHA12} quay.io/cryointhecloud/cryo-hub-image:${TAG}

    - name: Push Tags To Quay.io
      run: |
        docker push quay.io/cryointhecloud/cryo-hub-image:latest
        docker push quay.io/cryointhecloud/cryo-hub-image:${TAG}
